### PR TITLE
merge all mode additions

### PR DESCRIPTION
**Pull request by jipodine**
It seems that  jscheid/dtrt-indent is not active any more, but it could continue in the community, as along as the different modes are all added to the same branch.

Please notice that I lost js3-mode along the way... I also would like to know if something broke, in the modes that I do not use myself.

### CODE REVIEW

**Comment by rrthomas** [comment]
Thanks for this. What was the reason for getting rid of js3-mode and then adding back only js2-mode?

**Comment by rrthomas** [comment]
See also rrthomas/dtrt-indent#1

**Comment by jipodine** [comment]
It is a mistake, due to the different merges.

After a very quick overlook, I thought that we did not need the minor js modes any more, with the introduction of the javascript syntax. But it was not true, as js-mode and js2-mode use different names for the offset. Then I added back js2-mode, but I did not know for js3-mode, that I do not use. I found back your commit for js3-mode, so it may be fine now...

**Comment by rrthomas** [comment]
Thanks! Could you possibly squash the last three commits together, as that should remove some noise from the history.

**Comment by jipodine** [comment]
Right...

**Comment by rrthomas** [comment]
Could you please rebase this pull request on my fork?

**Comment by rrthomas** [comment]
@jipodine I've now read through all the patches. The various comments I've made indicate some small improvements to make the pull request easier to read as part of the history. Thanks again for your efforts with this. I've also contacted @jscheid to ask him whether he intends to do any more work on dtrt-indent, or whether I should take over.

**Comment by rrthomas** [comment]
@jipodine, I've just been given commit rights to upstream (thanks, @jscheid!) so I shall look at merging the pull requests there.

**Comment by jipodine** [comment]
Great, thank you for your participation.

**Pull request closed without merging**
